version: '1.0'
stages:
- clone
- build

steps:
  main_clone:
    title: Clone main repository
    type: git-clone
    stage: clone
    git: github
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: ${{CF_REVISION}}

  # Step cannot contain period for now
  build_zeppelin-0_8_1_spark-2_4_0_hadoop-3_1_0:
    type: build
    stage: build
    title: Build image zeppelin-0.8.1_spark-2.4.0_hadoop-3.1.0
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    tag: 0.8.1_spark-2.4.0_hadoop-3.1.0
    build_arguments:
    - ZEPPELIN_VERSION=0.8.1
    - SPARK_VERSION=2.4.0
    - HADOOP_VERSION=3.1.0
