version: '1.0'
stages:
- clone
- build
- test
- push

steps:
  main_clone:
    title: Clone main repository
    type: git-clone
    stage: clone
    git: github
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: ${{CF_REVISION}}

  # Step cannot contain period for now
  # DO NOT push to the actual tag first, only push after PR is merged
  build_zeppelin-master_spark-master-56f2887_hadoop-3_2_0_k8s:
    type: build
    stage: build
    title: Build image zeppelin-master_spark-master-56f2887_hadoop-3.2.0_k8s
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    tag: test_spark3-shims-fixed_spark-master-56f2887_hadoop-3.2.0_k8s
    build_arguments:
    - FROM_DOCKER_IMAGE=guangie88/spark-k8s-addons:master-56f2887_hadoop-3.2.0
    - ZEPPELIN_GIT_URL=https://github.com/guangie88/zeppelin.git
    - ZEPPELIN_REV=spark3-shims-fixed
    - ZEPPELIN_JAR_LOADER_VERSION=v0.2.0
    - PAC4J_AUTHORIZER_VERSION=v0.1.0

  test_zeppelin-master_spark-master-56f2887_hadoop-3_2_0_k8s:
    type: composition
    stage: test
    title: Test image zeppelin-master_spark-master-56f2887_hadoop-3.2.0_k8s
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    composition:
      version: '2'
      services:
        zeppelin:
          image: ${{build_zeppelin-master_spark-master-56f2887_hadoop-3_2_0_k8s}}
          ports:
          - 8080
    composition_candidates:
      tester:
        image: gempesaw/curl-jq:latest
        command: sh -c 'sleep 25 && [ "`curl -s http://zeppelin:8080/api/version | jq -r .status`" = "OK" ]'

  push_zeppelin-master_spark-master-56f2887_hadoop-3_2_0_k8s:
    type: push
    stage: push
    title: Push image zeppelin-master_spark-master-56f2887_hadoop-3.2.0_k8s
    candidate: ${{build_zeppelin-master_spark-master-56f2887_hadoop-3_2_0_k8s}}
    tag: spark3-shims-fixed_spark-master-56f2887_hadoop-3.2.0_k8s
    registry: cfcr
    when:
      branch:
        only:
        - master
